library(knitr)
library(rvest)
library(gsubfn)
library(tmap)
library(shiny)
library(ggplot2)
library(data.table)
library(dplyr)
library(tidyr)
library(readr)
library(lubridate)

options(gsubfn.engine="R")
